### ISSUE TITLE
Implementing Interrupt and exception ?

### ISSUE THREAD

**Issue by Hiroskey** [tilk/riscv-simple-sv#2]
Let me thank you for providing the repository. This is super good to learn RISC-V core !!

My question is that does the core have interrupt and exception? (As far as my looking, I cannot find them)
If not, will the core be extended to implement such functions and update the repository?

Best,

**Comment by tilk** [comment]
This is a minimal implementation meant for teaching - it's used for an entry-level course in University of Wrocław. If it gets extended by interrupt and exception support (or other features from the Privileged Architecture volume), it's only if it can be done without making the core more complex.
